In [3]:
import os

os.makedirs(os.path.join('..', 'data'), exist_ok=True)
data_file = os.path.join('..', 'data', 'house_tiny.csv')
with open(data_file, 'w') as f:
    f.write('NumRooms,Alley,Price\n')  # 列名
    f.write('NA,Pave,127500\n')  # 每行表示一个数据样本
    f.write('2,NA,106000\n')
    f.write('4,NA,178100\n')
    f.write('NA,NA,140000\n')

In [19]:
import pandas as pd
data = pd.read_csv(data_file)
data


NumRooms Alley   Price
0       NaN  Pave  127500
1       2.0   NaN  106000
2       4.0   NaN  178100
3       NaN   NaN  140000

In [26]:
inputs, outputs = data.iloc[:,0:2], data.iloc[:,2]

In [27]:
inputs

NumRooms Alley
0       NaN  Pave
1       2.0   NaN
2       4.0   NaN
3       NaN   NaN

In [28]:
outputs

0    127500
1    106000
2    178100
3    140000
Name: Price, dtype: int64

In [29]:
inputs = pd.get_dummies(inputs)
inputs

NumRooms  Alley_Pave
0       NaN        True
1       2.0       False
2       4.0       False
3       NaN       False

In [30]:
import torch
x= torch.tensor(inputs.to_numpy(dtype=float))
y =torch.tensor(outputs.to_numpy(dtype=float))

In [31]:
x

(tensor([[nan, 1.],
         [2., 0.],
         [4., 0.],
         [nan, 0.]], dtype=torch.float64),
 tensor([127500., 106000., 178100., 140000.], dtype=torch.float64))

In [32]:
y

tensor([127500., 106000., 178100., 140000.], dtype=torch.float64)