In [43]:
import torch
x = torch.arange(20, dtype=torch.float32).reshape(5,4)
x, x.sum()

(tensor([[ 0.,  1.,  2.,  3.],
         [ 4.,  5.,  6.,  7.],
         [ 8.,  9., 10., 11.],
         [12., 13., 14., 15.],
         [16., 17., 18., 19.]]),
 tensor(190.))

In [44]:
x_sum_axis =x.sum(axis=1)

In [45]:
x_sum_axis

tensor([ 6., 22., 38., 54., 70.])

In [46]:
x

tensor([[ 0.,  1.,  2.,  3.],
        [ 4.,  5.,  6.,  7.],
        [ 8.,  9., 10., 11.],
        [12., 13., 14., 15.],
        [16., 17., 18., 19.]])

In [48]:
x.cumsum(axis=0)


tensor([[ 0.,  1.,  2.,  3.],
        [ 4.,  6.,  8., 10.],
        [12., 15., 18., 21.],
        [24., 28., 32., 36.],
        [40., 45., 50., 55.]])

In [57]:
A = torch.arange(40).reshape(10, 4)

In [58]:
B = torch.arange(12).reshape(4, 3)
torch.mm(A,B)

tensor([[ 42,  48,  54],
        [114, 136, 158],
        [186, 224, 262],
        [258, 312, 366],
        [330, 400, 470],
        [402, 488, 574],
        [474, 576, 678],
        [546, 664, 782],
        [618, 752, 886],
        [690, 840, 990]])

In [59]:
A

tensor([[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11],
        [12, 13, 14, 15],
        [16, 17, 18, 19],
        [20, 21, 22, 23],
        [24, 25, 26, 27],
        [28, 29, 30, 31],
        [32, 33, 34, 35],
        [36, 37, 38, 39]])

In [60]:
B


tensor([[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8],
        [ 9, 10, 11]])